# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B1oGvj_xo2evlXPlDQl94-JnFBUzLtsp
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

iris = load_iris()

X=iris.data
Y=iris.target

print("特徴量の形:", X.shape)
print("ラベルの形:", Y.shape)
print("クラス名:", iris.target_names)

X_train,X_test,Y_train,Y_test =train_test_split(
    X,Y,test_size=0.2,random_state=42
)
print("学習データ:",X_train.shape)
print("テストデータ:",X_test.shape)

model=LogisticRegression(max_iter=200)
model.fit(X_train,Y_train)

Y_pred=model.predict(X_test)

print("予測結果:",Y_pred)
print("正解:",Y_test)

acc = accuracy_score(Y_test,Y_pred)
print("正解率:",acc)

print("分類レポート")
print(classification_report(Y_test,Y_pred,target_names=iris.target_names))

print("混同行列")
print(confusion_matrix(Y_test,Y_pred))